{{- $app := .Values.vminsert }}
{{- $hpa := $app.horizontalPodAutoscaler }}
{{- if $hpa.enabled }}
{{- $ctx := dict "helm" . "extraLabels" $app.extraLabels "appKey" "vminsert" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels: {{ include "victoria-metrics.vminsert.labels" $ctx | nindent 4 }}
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
spec:
  maxReplicas: {{ $hpa.maxReplicas }}
  minReplicas: {{ $hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vm.plain.fullname" $ctx }}
  metrics: {{ toYaml $hpa.metrics | nindent 4 }}
  {{- with $hpa.behavior }}
  behavior: {{ toYaml . | nindent 4 }}
  {{- end -}}
{{- end -}}
