{{- if .Values.extraVMAgent.enabled }}
{{- $ctx := dict "helm" . }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  labels: {{ include "victoria-metrics-distributed.labels" . | nindent 4 }}
  name: {{ .Values.extraVMAgent.name }}
  namespace: {{ include "vm.namespace" . }}
{{- $spec := (deepCopy .Values.extraVMAgent.spec) }}
{{- $remoteWrites := list (dict "url" (printf "%s/prometheus/api/v1/write" (include "vm.url" $ctx))) }}
{{- $_ := set $spec "remoteWrite" (concat $remoteWrites ($spec.remoteWrite | default list)) }}
spec: {{ tpl (toYaml $spec) . | nindent 2 }}
{{- end }}
